### ISSUE TITLE
Mixin 적용 오류

### ISSUE THREAD

**Issue by tmvkrpxl0** [coding-1ab/mega-modpack#4]
일부 mixin에서 다음과 같은 오류가 발생함:
```
[22:58:56] [pool-4-thread-1/DEBUG] [ne.mi.co.tr.CoreModBaseTransformer/COREMOD]: Transforming net/minecraft/world/level/block/LiquidBlock
[22:58:56] [pool-4-thread-1/DEBUG] [mixin/]: Mixing inject.MixinLiquidBlock from architectury-common.mixins.json into net.minecraft.world.level.block.LiquidBlock
[22:58:56] [pool-4-thread-1/DEBUG] [ne.mi.co.tr.CoreModBaseTransformer/COREMOD]: Transforming net/minecraft/world/level/block/StairBlock
[22:58:56] [pool-4-thread-1/DEBUG] [ne.mi.co.tr.CoreModBaseTransformer/COREMOD]: Transforming net/minecraft/world/level/block/FlowerPotBlock
[22:58:56] [pool-4-thread-1/DEBUG] [mixin/]: Mixing sign.MixinAbstractBlockSettings from doapi.mixins.json into net.minecraft.world.level.block.state.BlockBehaviour$Properties
[22:58:57] [pool-4-thread-1/DEBUG] [mixin/]: Mixing MixinFallingBlockEntity from architectury.mixins.json into net.minecraft.world.entity.item.FallingBlockEntity
[22:58:57] [pool-4-thread-1/FATAL] [mixin/]: Mixin apply failed architectury.mixins.json:MixinFallingBlockEntity -> net.minecraft.world.entity.item.FallingBlockEntity: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field f_31946_ was not located in the target class net.minecraft.world.entity.item.FallingBlockEntity. Using refmap architectury-forge-refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field f_31946_ was not located in the target class net.minecraft.world.entity.item.FallingBlockEntity. Using refmap architectury-forge-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:629) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:305) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:280) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1288) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
```
(architectury-api 적용시 발생하는 오류)
아마 Loom이 사용하는 Mixin으로 전환하면 해결될 것 같기도 함.

# 테스트
Big-Brain은 작고 종속성 없는 모드라 테스트에 안성맞춤. `includeBuild`로 불러온 다음 
```
mod("tallestegg.bigbrain:Big-Brain:1.20-1.7.3")
```
로 테스트 할 시 위와 같은 오류 발생.

**Comment by tmvkrpxl0** [comment]
[Fabric Mixin](https://github.com/Sinytra/MixinTransmogrifier/tree/agentful) 설치 이후 오류가 다른 것으로 바뀜. 최소한 Mixin 적용 실패 오류는 아닌듯.
```
[234월2024 23:21:16.396] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: doapi, class de.cristelknight.doapi.forge.DoApiForge
java.lang.NoSuchFieldError: f_256747_
	at de.cristelknight.doapi.common.registry.DoApiBlocks.<clinit>(DoApiBlocks.java:20) ~[letsdo-API-forge-1.2.9-forge.jar%23192!/:?]
	at de.cristelknight.doapi.DoApi.init(DoApi.java:16) ~[letsdo-API-forge-1.2.9-forge.jar%23192!/:?]
	at de.cristelknight.doapi.forge.DoApiForge.<init>(DoApiForge.java:18) ~[letsdo-API-forge-1.2.9-forge.jar%23192!/:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
```

**Comment by tmvkrpxl0** [comment]
아 그냥 오류 메세지만 더 친절해진 거구나

**Comment by tmvkrpxl0** [comment]
루트 프로젝트를 Architectury로 갈아타볼까?

**Comment by tmvkrpxl0** [comment]
includeBuild는 모드 개발 환경에서 불안정해서 쓰지 말라고 한다..
